# Generated by Django 4.1.13 on 2024-05-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PO',
            new_name='PurchaseOrder',
        ),
    ]
