# Generated by Django 4.1.13 on 2024-05-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_po_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='average_response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='fulfillment_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='on_time_delivery_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='quality_rating_rate',
            field=models.FloatField(default=0),
        ),
    ]
